[project]
name = "ansible.infra.paultibbetts.uk"
version = "0.1.0"
description = "The Ansible for the infrastructure that makes up paultibbetts.uk"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "ansible-core>=2.20.1"
]

[dependency-groups]
dev = [
    "molecule>=25.12.0",
]
