---
- hosts: pi
  become: true
  roles:
    - { role: server, tags: [server] }
    - { role: firewall, tags: [firewall] }
    - { role: web, tags: [web] }
    - { role: paultibbetts.caddy, tags: [caddy] }
